// src/lib/constants.js
export const ADMIN_EMAILS = ['nfe@savantiplasticos.com.br'];

export const MAQUINAS = ['P1','P2','P3','P4','I1','I2','I3','I4','I5','I6']

export const STATUS = ['AGUARDANDO','PRODUZINDO','BAIXA_EFICIENCIA','PARADA']

export const MOTIVOS_PARADA = [
  'SET UP','TROCA DE COR','FIM DE SEMANA','INÍCIO DE MÁQUINA','FALTA DE OPERADOR / PREPARADOR',
  'TRY-OUT / TESTE','QUALIDADE / REGULAGEM','MANUTENÇÃO ELÉTRICA','MANUTENÇÃO MECÂNICA',
  'FALTA DE PEDIDO','FIM OP','FALTA DE ABASTECIMENTO','FALTA DE INSUMOS','FALTA DE ENERGIA ELÉTRICA','FALTA DE PROGRAMAÇÃO',
]